### PR TITLE
Week3 - Will K - PR resubmit again

### PR DESCRIPTION
**Pull request by willkotheimer**

### CODE REVIEW

**Comment by willkotheimer** [comment]
Just fixed double quotes after you said to!

**Comment by brownabs** [comment]
2:1   error  Strings must use singlequote  quotes
    7:19  error  Strings must use singlequote  quotes
   77:39  error  Missing semicolon             semi
  116:24  error  Missing semicolon             semi
  139:33  error  Missing semicolon             semi

**Comment by brownabs** [comment]
Were you able to delete the console logs and put in place the missing semi-colons?

**Comment by brownabs** [comment]
Then add commit and submit a new pull request

**Comment by willkotheimer** [comment]
Fixed!

**Comment by brownabs** [comment]
line one is still double quotes

**Comment by willkotheimer** [comment]
Oh, I thought that the "use strict" needed to be in double. I can change that!

**Pull request closed without merging**
